#!/bin/bash

echo "🔍 GOOGLE OAUTH CONFIGURATION CHECKER"
echo "====================================="

echo ""
echo "🔧 Firebase Configuration Check:"
echo "Project ID: last-35eb7"
echo "Auth Domain: last-35eb7.firebaseapp.com"
echo "Expected OAuth Handler: https://last-35eb7.firebaseapp.com/__/auth/handler"
echo ""

echo "🌐 Required Authorized Domains in Firebase:"
echo "- localhost"
echo "- 127.0.0.1"
echo "- fictional-space-guide-x556vjvrxwx53p4gp-9002.githubpreview.dev"
echo "- last-35eb7.firebaseapp.com"
echo ""

echo "🔑 Google Cloud Console URLs to Check:"
echo "1. OAuth 2.0 Client IDs:"
echo "   https://console.cloud.google.com/apis/credentials?project=last-35eb7"
echo ""
echo "2. OAuth Consent Screen:"
echo "   https://console.cloud.google.com/apis/credentials/consent?project=last-35eb7"
echo ""
echo "3. Enabled APIs:"
echo "   https://console.cloud.google.com/apis/library?project=last-35eb7"
echo "   (Ensure 'Google+ API' or 'Google Identity' is enabled)"
echo ""

echo "🎯 Firebase Console URLs to Check:"
echo "1. Authentication Providers:"
echo "   https://console.firebase.google.com/project/last-35eb7/authentication/providers"
echo ""
echo "2. Authentication Settings (Authorized Domains):"
echo "   https://console.firebase.google.com/project/last-35eb7/authentication/settings"
echo ""

echo "✅ What Should Be Configured:"
echo "1. Google Cloud Console OAuth 2.0 Client ID with:"
echo "   - Application type: Web application"
echo "   - Authorized redirect URIs: https://last-35eb7.firebaseapp.com/__/auth/handler"
echo "   - Authorized JavaScript origins: https://last-35eb7.firebaseapp.com"
echo ""
echo "2. OAuth Consent Screen with:"
echo "   - App name: EDTECH AI"
echo "   - Support email configured"
echo "   - Your email added as test user (if in Testing mode)"
echo ""
echo "3. Firebase Console Google Provider with:"
echo "   - Status: Enabled"
echo "   - Client ID: (copied from Google Cloud Console)"
echo "   - Client Secret: (copied from Google Cloud Console)"
echo ""

echo "🚨 Common Issues That Cause auth/internal-error:"
echo "1. OAuth client not created in Google Cloud Console"
echo "2. Client ID mismatch between Firebase and Google Cloud Console"
echo "3. Missing redirect URIs in OAuth client"
echo "4. OAuth consent screen not configured"
echo "5. User not added as test user in OAuth consent screen"
echo "6. Required APIs not enabled in Google Cloud Console"
echo ""

echo "🔧 Next Steps:"
echo "1. Run: chmod +x fix-google-oauth-complete.sh && ./fix-google-oauth-complete.sh"
echo "2. Follow the step-by-step instructions"
echo "3. Test Google OAuth after configuration"
echo ""

echo "📝 To start development server after fix:"
echo "npm run dev"
